spring.datasource.url=jdbc:postgresql://localhost:5432/sentinelcore
spring.datasource.username=postgres
spring.datasource.password=hellokitty

spring.jpa.hibernate.ddl-auto=update
jwt.secret=U2VudGluZWxDb3JlTW9uaXRvcmluZ1NlY3JldEtleTIwMjY=
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080